# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI
on: push

jobs:
  ci:
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.2]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install
      run: poetry install
    - name: Run black & isort
      run: |
        poetry run black --diff --check ziggurat
        poetry run isort --diff --check ziggurat
        poetry run black --diff --check tests
        poetry run isort --diff --check tests
    - name: Run mypy
      run: poetry run mypy ziggurat
    - name: Run Tests
      run: poetry run python -m unittest discover
